// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using POCO;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace POCO
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Mock.Implementation;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ViewsProperty
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("selectable", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Selectable { get; set; }

        [JsonProperty("supportsMultipleDefinitions", NullValueHandling = NullValueHandling.Ignore)]
        public bool? SupportsMultipleDefinitions { get; set; }

        [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
        public string Icon { get; set; }

        [JsonProperty("builder", NullValueHandling = NullValueHandling.Ignore)]
        public string Builder { get; set; }

        [JsonProperty("definitions", NullValueHandling = NullValueHandling.Ignore)]
        public List<Definition> Definitions { get; set; }
    }

    public partial class Definition
    {
        [JsonProperty("definition", NullValueHandling = NullValueHandling.Ignore)]
        public string DefinitionName { get; set; }

        [JsonProperty("definitionLabels", NullValueHandling = NullValueHandling.Ignore)]
        public DefinitionLabels DefinitionLabels { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public string Template { get; set; }

        [JsonProperty("rendition", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Rendition { get; set; }

        [JsonProperty("builder", NullValueHandling = NullValueHandling.Ignore)]
        public string Builder { get; set; }

        [JsonProperty("showDefinitionName", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ShowDefinitionName { get; set; }

        [JsonProperty("enableQuickEdit", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EnableQuickEdit { get; set; }

        [JsonProperty("detailsComponent")]
        public object DetailsComponent { get; set; }

        [JsonProperty("templateOperation", NullValueHandling = NullValueHandling.Ignore)]
        public TemplateOperation TemplateOperation { get; set; }

        [JsonProperty("fields", NullValueHandling = NullValueHandling.Ignore)]
        public List<Field> Fields { get; set; }

        [JsonProperty("actions", NullValueHandling = NullValueHandling.Ignore)]
        public List<Action> Actions { get; set; }

        [JsonProperty("moreActionsSettings", NullValueHandling = NullValueHandling.Ignore)]
        public MoreActionsSettings MoreActionsSettings { get; set; }

        [JsonProperty("indicators", NullValueHandling = NullValueHandling.Ignore)]
        public List<Indicator> Indicators { get; set; }
    }

    public partial class Action
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("category", NullValueHandling = NullValueHandling.Ignore)]
        public string Category { get; set; }

        [JsonProperty("renditions", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Renditions { get; set; }

        [JsonProperty("permissionsToLoad", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> PermissionsToLoad { get; set; }

        [JsonProperty("display", NullValueHandling = NullValueHandling.Ignore)]
        public string Display { get; set; }

        [JsonProperty("buttonStyle", NullValueHandling = NullValueHandling.Ignore)]
        public string ButtonStyle { get; set; }

        [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
        public string Icon { get; set; }

        [JsonProperty("customLabel", NullValueHandling = NullValueHandling.Ignore)]
        public string CustomLabel { get; set; }

        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> ActionRequired { get; set; }

        [JsonProperty("optional", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> Optional { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("messages", NullValueHandling = NullValueHandling.Ignore)]
        public ActionMessages Messages { get; set; }
    }

    public partial class ActionMessages
    {
        [JsonProperty("Inlinepreview", NullValueHandling = NullValueHandling.Ignore)]
        public string Inlinepreview { get; set; }

        [JsonProperty("Addtosavedselection", NullValueHandling = NullValueHandling.Ignore)]
        public string Addtosavedselection { get; set; }

        [JsonProperty("Removefromsavedselection", NullValueHandling = NullValueHandling.Ignore)]
        public string Removefromsavedselection { get; set; }
    }

    public partial class DefinitionLabels
    {
        [JsonProperty("en-US", NullValueHandling = NullValueHandling.Ignore)]
        public string EnUs { get; set; }
    }

    public partial class Field
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("control", NullValueHandling = NullValueHandling.Ignore)]
        public string Control { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("showHelpText", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ShowHelpText { get; set; }

        [JsonProperty("helpTextFormat", NullValueHandling = NullValueHandling.Ignore)]
        public string HelpTextFormat { get; set; }
    }

    public partial class Indicator
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("display", NullValueHandling = NullValueHandling.Ignore)]
        public string Display { get; set; }

        [JsonProperty("title", NullValueHandling = NullValueHandling.Ignore)]
        public string Title { get; set; }

        [JsonProperty("backgroundColor", NullValueHandling = NullValueHandling.Ignore)]
        public string BackgroundColor { get; set; }

        [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
        public string Icon { get; set; }

        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> IndicatorRequired { get; set; }

        [JsonProperty("optional", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> Optional { get; set; }

        [JsonProperty("color", NullValueHandling = NullValueHandling.Ignore)]
        public string Color { get; set; }

        [JsonProperty("messages", NullValueHandling = NullValueHandling.Ignore)]
        public IndicatorMessages Messages { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("fields", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Fields { get; set; }
    }

    public partial class IndicatorMessages
    {
        [JsonProperty("Lock", NullValueHandling = NullValueHandling.Ignore)]
        public string Lock { get; set; }

        [JsonProperty("Duplicatesexist", NullValueHandling = NullValueHandling.Ignore)]
        public string Duplicatesexist { get; set; }

        [JsonProperty("Processing", NullValueHandling = NullValueHandling.Ignore)]
        public string Processing { get; set; }

        [JsonProperty("Draft", NullValueHandling = NullValueHandling.Ignore)]
        public string Draft { get; set; }
    }

    public partial class MoreActionsSettings
    {
        [JsonProperty("moreOptionsDisplay", NullValueHandling = NullValueHandling.Ignore)]
        public string MoreOptionsDisplay { get; set; }

        [JsonProperty("moreOptionsButtonStyle", NullValueHandling = NullValueHandling.Ignore)]
        public string MoreOptionsButtonStyle { get; set; }
    }

    public partial class TemplateOperation
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("category", NullValueHandling = NullValueHandling.Ignore)]
        public string Category { get; set; }

        [JsonProperty("permissionsToLoad", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> PermissionsToLoad { get; set; }

        [JsonProperty("display", NullValueHandling = NullValueHandling.Ignore)]
        public string Display { get; set; }

        [JsonProperty("buttonStyle", NullValueHandling = NullValueHandling.Ignore)]
        public string ButtonStyle { get; set; }

        [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
        public string Icon { get; set; }

        [JsonProperty("customLabel", NullValueHandling = NullValueHandling.Ignore)]
        public string CustomLabel { get; set; }

        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public List<RequiredElement> TemplateOperationRequired { get; set; }

        [JsonProperty("optional", NullValueHandling = NullValueHandling.Ignore)]
        public List<Optional> Optional { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("messages", NullValueHandling = NullValueHandling.Ignore)]
        public TemplateOperationMessages Messages { get; set; }
    }

    public partial class TemplateOperationMessages
    {
        [JsonProperty("Viewdetailpage", NullValueHandling = NullValueHandling.Ignore)]
        public string Viewdetailpage { get; set; }
    }

    public partial class Optional
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Value { get; set; }
    }

    public partial class RequiredElement
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        public string Value { get; set; }
    }
}
